baseURL = "https://izabellaaaq.github.io/semelhanteSpotify/"
languageCode = "pt-BR"
title = "Henrique e Juliano"
theme = "hugo-nuo"
publishDir = "docs"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true



